---
# Make sure nginx is not installed

- name: Remove previous/installed nginx
  apt:
    pkg:
      - nginx
      - nginx-common
    state: absent
    purge: true

- name: Further check
  become: yes
  shell: apt remove --purge nginx*

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Update cache
  apt:
    update_cache: yes

- name: Remove nginx from apt sources
  become: yes
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/sources.list.d/nginx.list
    - /etc/apt/sources.list.d/nginx.list.save
    - /etc/apt/sources.list.d/ondrej-ubuntu-nginx-kinetic.list
